// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/services/services.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	types "github.com/proto/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("proto/services/services.proto", fileDescriptor_31a22b2bda9d2e46) }

var fileDescriptor_31a22b2bda9d2e46 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xb7, 0x17, 0x6d, 0x07, 0x7a, 0x30, 0x7a, 0x90, 0x82, 0x97, 0x7d, 0x80, 0x2d, 0xd6,
	0x83, 0xa0, 0x78, 0x5a, 0xa1, 0xa7, 0x42, 0xe9, 0x3e, 0x41, 0xda, 0xce, 0x21, 0xd0, 0x24, 0x75,
	0x27, 0x15, 0x7c, 0x71, 0xf1, 0x28, 0xc9, 0x66, 0x93, 0x71, 0xdd, 0x5b, 0xe6, 0xe3, 0xff, 0xf8,
	0xf9, 0x09, 0x3c, 0x9c, 0x5b, 0xeb, 0xec, 0x92, 0xb0, 0xfd, 0x54, 0x07, 0xa4, 0xf4, 0xa8, 0x02,
	0x17, 0xd3, 0xfe, 0x5e, 0xdc, 0x77, 0x41, 0xf7, 0x75, 0x46, 0x5a, 0x1e, 0xac, 0xd6, 0xd6, 0x74,
	0x99, 0xd5, 0xf7, 0x04, 0x66, 0xef, 0x1b, 0x65, 0x70, 0x23, 0x95, 0x11, 0xaf, 0x30, 0x6f, 0x50,
	0x9e, 0xb6, 0x2d, 0xd6, 0x56, 0x6b, 0xe5, 0xc4, 0x6d, 0x15, 0x9c, 0x2a, 0x91, 0x1d, 0x7e, 0x2c,
	0x46, 0x20, 0x95, 0x85, 0x78, 0x01, 0xf0, 0x72, 0x34, 0xef, 0x62, 0x28, 0x23, 0xaf, 0x8e, 0x51,
	0xef, 0xbe, 0xc1, 0x7c, 0x8d, 0xa6, 0x96, 0xe6, 0xa8, 0x8e, 0xd2, 0x21, 0x25, 0x3d, 0x23, 0xae,
	0x73, 0xea, 0xf5, 0x47, 0xb8, 0x5e, 0xa3, 0xd9, 0xda, 0xc6, 0x89, 0x9b, 0x18, 0x89, 0xb7, 0xb7,
	0xfe, 0x21, 0x2a, 0x8b, 0xd5, 0xcf, 0x04, 0xa6, 0x61, 0x78, 0x73, 0xd9, 0xb3, 0xdd, 0x3b, 0xa4,
	0xcb, 0xe9, 0xcf, 0xee, 0x8e, 0x0c, 0x76, 0xf7, 0x90, 0xed, 0x8e, 0x26, 0x5f, 0x98, 0xd5, 0x31,
	0xea, 0xdd, 0x67, 0x98, 0xd5, 0xd2, 0x0c, 0x4a, 0x13, 0xe1, 0xa5, 0x0c, 0xc6, 0xd2, 0xb8, 0x85,
	0x97, 0x66, 0xc4, 0x4b, 0x39, 0xa5, 0xb2, 0xd8, 0x5f, 0x85, 0xaf, 0x7f, 0xfa, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xdf, 0x56, 0xf3, 0x9b, 0x3f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DMineMainClient is the client API for DMineMain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DMineMainClient interface {
	SealPreCommit(ctx context.Context, in *types.PreCommitReq, opts ...grpc.CallOption) (*types.PreCommitRes, error)
	SealCommit(ctx context.Context, in *types.SealCommitReq, opts ...grpc.CallOption) (*types.SealCommitRes, error)
	GenCandidates(ctx context.Context, in *types.CandidatesReq, opts ...grpc.CallOption) (*types.CandidatesRes, error)
	GenPoSt(ctx context.Context, in *types.GenPoStReq, opts ...grpc.CallOption) (*types.GenPoStRes, error)
}

type dMineMainClient struct {
	cc *grpc.ClientConn
}

func NewDMineMainClient(cc *grpc.ClientConn) DMineMainClient {
	return &dMineMainClient{cc}
}

func (c *dMineMainClient) SealPreCommit(ctx context.Context, in *types.PreCommitReq, opts ...grpc.CallOption) (*types.PreCommitRes, error) {
	out := new(types.PreCommitRes)
	err := c.cc.Invoke(ctx, "/services.DMineMain/SealPreCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMineMainClient) SealCommit(ctx context.Context, in *types.SealCommitReq, opts ...grpc.CallOption) (*types.SealCommitRes, error) {
	out := new(types.SealCommitRes)
	err := c.cc.Invoke(ctx, "/services.DMineMain/SealCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMineMainClient) GenCandidates(ctx context.Context, in *types.CandidatesReq, opts ...grpc.CallOption) (*types.CandidatesRes, error) {
	out := new(types.CandidatesRes)
	err := c.cc.Invoke(ctx, "/services.DMineMain/GenCandidates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMineMainClient) GenPoSt(ctx context.Context, in *types.GenPoStReq, opts ...grpc.CallOption) (*types.GenPoStRes, error) {
	out := new(types.GenPoStRes)
	err := c.cc.Invoke(ctx, "/services.DMineMain/GenPoSt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DMineMainServer is the server API for DMineMain service.
type DMineMainServer interface {
	SealPreCommit(context.Context, *types.PreCommitReq) (*types.PreCommitRes, error)
	SealCommit(context.Context, *types.SealCommitReq) (*types.SealCommitRes, error)
	GenCandidates(context.Context, *types.CandidatesReq) (*types.CandidatesRes, error)
	GenPoSt(context.Context, *types.GenPoStReq) (*types.GenPoStRes, error)
}

// UnimplementedDMineMainServer can be embedded to have forward compatible implementations.
type UnimplementedDMineMainServer struct {
}

func (*UnimplementedDMineMainServer) SealPreCommit(ctx context.Context, req *types.PreCommitReq) (*types.PreCommitRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SealPreCommit not implemented")
}
func (*UnimplementedDMineMainServer) SealCommit(ctx context.Context, req *types.SealCommitReq) (*types.SealCommitRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SealCommit not implemented")
}
func (*UnimplementedDMineMainServer) GenCandidates(ctx context.Context, req *types.CandidatesReq) (*types.CandidatesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenCandidates not implemented")
}
func (*UnimplementedDMineMainServer) GenPoSt(ctx context.Context, req *types.GenPoStReq) (*types.GenPoStRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenPoSt not implemented")
}

func RegisterDMineMainServer(s *grpc.Server, srv DMineMainServer) {
	s.RegisterService(&_DMineMain_serviceDesc, srv)
}

func _DMineMain_SealPreCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.PreCommitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMineMainServer).SealPreCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DMineMain/SealPreCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMineMainServer).SealPreCommit(ctx, req.(*types.PreCommitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMineMain_SealCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.SealCommitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMineMainServer).SealCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DMineMain/SealCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMineMainServer).SealCommit(ctx, req.(*types.SealCommitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMineMain_GenCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.CandidatesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMineMainServer).GenCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DMineMain/GenCandidates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMineMainServer).GenCandidates(ctx, req.(*types.CandidatesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMineMain_GenPoSt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GenPoStReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMineMainServer).GenPoSt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DMineMain/GenPoSt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMineMainServer).GenPoSt(ctx, req.(*types.GenPoStReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DMineMain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.DMineMain",
	HandlerType: (*DMineMainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SealPreCommit",
			Handler:    _DMineMain_SealPreCommit_Handler,
		},
		{
			MethodName: "SealCommit",
			Handler:    _DMineMain_SealCommit_Handler,
		},
		{
			MethodName: "GenCandidates",
			Handler:    _DMineMain_GenCandidates_Handler,
		},
		{
			MethodName: "GenPoSt",
			Handler:    _DMineMain_GenPoSt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/services/services.proto",
}

// DMineSubClient is the client API for DMineSub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DMineSubClient interface {
	SealPreResult(ctx context.Context, in *types.PreResultReq, opts ...grpc.CallOption) (*types.PreResultRes, error)
	SealResult(ctx context.Context, in *types.SealResultReq, opts ...grpc.CallOption) (*types.SealResultRes, error)
	CanResult(ctx context.Context, in *types.CanResultReq, opts ...grpc.CallOption) (*types.CanResultRes, error)
	PoStResult(ctx context.Context, in *types.PoStResultReq, opts ...grpc.CallOption) (*types.PoStResultRes, error)
}

type dMineSubClient struct {
	cc *grpc.ClientConn
}

func NewDMineSubClient(cc *grpc.ClientConn) DMineSubClient {
	return &dMineSubClient{cc}
}

func (c *dMineSubClient) SealPreResult(ctx context.Context, in *types.PreResultReq, opts ...grpc.CallOption) (*types.PreResultRes, error) {
	out := new(types.PreResultRes)
	err := c.cc.Invoke(ctx, "/services.DMineSub/SealPreResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMineSubClient) SealResult(ctx context.Context, in *types.SealResultReq, opts ...grpc.CallOption) (*types.SealResultRes, error) {
	out := new(types.SealResultRes)
	err := c.cc.Invoke(ctx, "/services.DMineSub/SealResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMineSubClient) CanResult(ctx context.Context, in *types.CanResultReq, opts ...grpc.CallOption) (*types.CanResultRes, error) {
	out := new(types.CanResultRes)
	err := c.cc.Invoke(ctx, "/services.DMineSub/CanResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMineSubClient) PoStResult(ctx context.Context, in *types.PoStResultReq, opts ...grpc.CallOption) (*types.PoStResultRes, error) {
	out := new(types.PoStResultRes)
	err := c.cc.Invoke(ctx, "/services.DMineSub/PoStResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DMineSubServer is the server API for DMineSub service.
type DMineSubServer interface {
	SealPreResult(context.Context, *types.PreResultReq) (*types.PreResultRes, error)
	SealResult(context.Context, *types.SealResultReq) (*types.SealResultRes, error)
	CanResult(context.Context, *types.CanResultReq) (*types.CanResultRes, error)
	PoStResult(context.Context, *types.PoStResultReq) (*types.PoStResultRes, error)
}

// UnimplementedDMineSubServer can be embedded to have forward compatible implementations.
type UnimplementedDMineSubServer struct {
}

func (*UnimplementedDMineSubServer) SealPreResult(ctx context.Context, req *types.PreResultReq) (*types.PreResultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SealPreResult not implemented")
}
func (*UnimplementedDMineSubServer) SealResult(ctx context.Context, req *types.SealResultReq) (*types.SealResultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SealResult not implemented")
}
func (*UnimplementedDMineSubServer) CanResult(ctx context.Context, req *types.CanResultReq) (*types.CanResultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CanResult not implemented")
}
func (*UnimplementedDMineSubServer) PoStResult(ctx context.Context, req *types.PoStResultReq) (*types.PoStResultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PoStResult not implemented")
}

func RegisterDMineSubServer(s *grpc.Server, srv DMineSubServer) {
	s.RegisterService(&_DMineSub_serviceDesc, srv)
}

func _DMineSub_SealPreResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.PreResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMineSubServer).SealPreResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DMineSub/SealPreResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMineSubServer).SealPreResult(ctx, req.(*types.PreResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMineSub_SealResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.SealResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMineSubServer).SealResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DMineSub/SealResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMineSubServer).SealResult(ctx, req.(*types.SealResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMineSub_CanResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.CanResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMineSubServer).CanResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DMineSub/CanResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMineSubServer).CanResult(ctx, req.(*types.CanResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMineSub_PoStResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.PoStResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMineSubServer).PoStResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DMineSub/PoStResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMineSubServer).PoStResult(ctx, req.(*types.PoStResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DMineSub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.DMineSub",
	HandlerType: (*DMineSubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SealPreResult",
			Handler:    _DMineSub_SealPreResult_Handler,
		},
		{
			MethodName: "SealResult",
			Handler:    _DMineSub_SealResult_Handler,
		},
		{
			MethodName: "CanResult",
			Handler:    _DMineSub_CanResult_Handler,
		},
		{
			MethodName: "PoStResult",
			Handler:    _DMineSub_PoStResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/services/services.proto",
}
