// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PreCommitReq struct {
	SecSize              uint64             `protobuf:"varint,1,opt,name=SecSize,proto3" json:"SecSize,omitempty"`
	SecID                uint64             `protobuf:"varint,2,opt,name=SecID,proto3" json:"SecID,omitempty"`
	ProverID             []byte             `protobuf:"bytes,3,opt,name=ProverID,proto3" json:"ProverID,omitempty"`
	Tickets              []byte             `protobuf:"bytes,4,opt,name=Tickets,proto3" json:"Tickets,omitempty"`
	PubInfo              []*PublicPieceInfo `protobuf:"bytes,5,rep,name=PubInfo,proto3" json:"PubInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PreCommitReq) Reset()         { *m = PreCommitReq{} }
func (m *PreCommitReq) String() string { return proto.CompactTextString(m) }
func (*PreCommitReq) ProtoMessage()    {}
func (*PreCommitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *PreCommitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreCommitReq.Unmarshal(m, b)
}
func (m *PreCommitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreCommitReq.Marshal(b, m, deterministic)
}
func (m *PreCommitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreCommitReq.Merge(m, src)
}
func (m *PreCommitReq) XXX_Size() int {
	return xxx_messageInfo_PreCommitReq.Size(m)
}
func (m *PreCommitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PreCommitReq.DiscardUnknown(m)
}

var xxx_messageInfo_PreCommitReq proto.InternalMessageInfo

func (m *PreCommitReq) GetSecSize() uint64 {
	if m != nil {
		return m.SecSize
	}
	return 0
}

func (m *PreCommitReq) GetSecID() uint64 {
	if m != nil {
		return m.SecID
	}
	return 0
}

func (m *PreCommitReq) GetProverID() []byte {
	if m != nil {
		return m.ProverID
	}
	return nil
}

func (m *PreCommitReq) GetTickets() []byte {
	if m != nil {
		return m.Tickets
	}
	return nil
}

func (m *PreCommitReq) GetPubInfo() []*PublicPieceInfo {
	if m != nil {
		return m.PubInfo
	}
	return nil
}

type PublicPieceInfo struct {
	Size                 uint64   `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	CommP                []byte   `protobuf:"bytes,2,opt,name=CommP,proto3" json:"CommP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicPieceInfo) Reset()         { *m = PublicPieceInfo{} }
func (m *PublicPieceInfo) String() string { return proto.CompactTextString(m) }
func (*PublicPieceInfo) ProtoMessage()    {}
func (*PublicPieceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *PublicPieceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicPieceInfo.Unmarshal(m, b)
}
func (m *PublicPieceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicPieceInfo.Marshal(b, m, deterministic)
}
func (m *PublicPieceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicPieceInfo.Merge(m, src)
}
func (m *PublicPieceInfo) XXX_Size() int {
	return xxx_messageInfo_PublicPieceInfo.Size(m)
}
func (m *PublicPieceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicPieceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PublicPieceInfo proto.InternalMessageInfo

func (m *PublicPieceInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PublicPieceInfo) GetCommP() []byte {
	if m != nil {
		return m.CommP
	}
	return nil
}

type PreCommitRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreCommitRes) Reset()         { *m = PreCommitRes{} }
func (m *PreCommitRes) String() string { return proto.CompactTextString(m) }
func (*PreCommitRes) ProtoMessage()    {}
func (*PreCommitRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *PreCommitRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreCommitRes.Unmarshal(m, b)
}
func (m *PreCommitRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreCommitRes.Marshal(b, m, deterministic)
}
func (m *PreCommitRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreCommitRes.Merge(m, src)
}
func (m *PreCommitRes) XXX_Size() int {
	return xxx_messageInfo_PreCommitRes.Size(m)
}
func (m *PreCommitRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PreCommitRes.DiscardUnknown(m)
}

var xxx_messageInfo_PreCommitRes proto.InternalMessageInfo

type SealCommitReq struct {
	SecSize              uint64             `protobuf:"varint,1,opt,name=SecSize,proto3" json:"SecSize,omitempty"`
	SecID                uint64             `protobuf:"varint,2,opt,name=SecID,proto3" json:"SecID,omitempty"`
	ProverID             []byte             `protobuf:"bytes,3,opt,name=ProverID,proto3" json:"ProverID,omitempty"`
	Tickets              []byte             `protobuf:"bytes,4,opt,name=Tickets,proto3" json:"Tickets,omitempty"`
	PubInfo              []*PublicPieceInfo `protobuf:"bytes,5,rep,name=PubInfo,proto3" json:"PubInfo,omitempty"`
	RawCommit            []*PreResultReq    `protobuf:"bytes,6,rep,name=RawCommit,proto3" json:"RawCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SealCommitReq) Reset()         { *m = SealCommitReq{} }
func (m *SealCommitReq) String() string { return proto.CompactTextString(m) }
func (*SealCommitReq) ProtoMessage()    {}
func (*SealCommitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *SealCommitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SealCommitReq.Unmarshal(m, b)
}
func (m *SealCommitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SealCommitReq.Marshal(b, m, deterministic)
}
func (m *SealCommitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SealCommitReq.Merge(m, src)
}
func (m *SealCommitReq) XXX_Size() int {
	return xxx_messageInfo_SealCommitReq.Size(m)
}
func (m *SealCommitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SealCommitReq.DiscardUnknown(m)
}

var xxx_messageInfo_SealCommitReq proto.InternalMessageInfo

func (m *SealCommitReq) GetSecSize() uint64 {
	if m != nil {
		return m.SecSize
	}
	return 0
}

func (m *SealCommitReq) GetSecID() uint64 {
	if m != nil {
		return m.SecID
	}
	return 0
}

func (m *SealCommitReq) GetProverID() []byte {
	if m != nil {
		return m.ProverID
	}
	return nil
}

func (m *SealCommitReq) GetTickets() []byte {
	if m != nil {
		return m.Tickets
	}
	return nil
}

func (m *SealCommitReq) GetPubInfo() []*PublicPieceInfo {
	if m != nil {
		return m.PubInfo
	}
	return nil
}

func (m *SealCommitReq) GetRawCommit() []*PreResultReq {
	if m != nil {
		return m.RawCommit
	}
	return nil
}

type SealCommitRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SealCommitRes) Reset()         { *m = SealCommitRes{} }
func (m *SealCommitRes) String() string { return proto.CompactTextString(m) }
func (*SealCommitRes) ProtoMessage()    {}
func (*SealCommitRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *SealCommitRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SealCommitRes.Unmarshal(m, b)
}
func (m *SealCommitRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SealCommitRes.Marshal(b, m, deterministic)
}
func (m *SealCommitRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SealCommitRes.Merge(m, src)
}
func (m *SealCommitRes) XXX_Size() int {
	return xxx_messageInfo_SealCommitRes.Size(m)
}
func (m *SealCommitRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SealCommitRes.DiscardUnknown(m)
}

var xxx_messageInfo_SealCommitRes proto.InternalMessageInfo

type GenPoStReq struct {
	Ip                   []byte   `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Seed                 []byte   `protobuf:"bytes,2,opt,name=Seed,proto3" json:"Seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenPoStReq) Reset()         { *m = GenPoStReq{} }
func (m *GenPoStReq) String() string { return proto.CompactTextString(m) }
func (*GenPoStReq) ProtoMessage()    {}
func (*GenPoStReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *GenPoStReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenPoStReq.Unmarshal(m, b)
}
func (m *GenPoStReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenPoStReq.Marshal(b, m, deterministic)
}
func (m *GenPoStReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenPoStReq.Merge(m, src)
}
func (m *GenPoStReq) XXX_Size() int {
	return xxx_messageInfo_GenPoStReq.Size(m)
}
func (m *GenPoStReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenPoStReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenPoStReq proto.InternalMessageInfo

func (m *GenPoStReq) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *GenPoStReq) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

type GenPoStRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenPoStRes) Reset()         { *m = GenPoStRes{} }
func (m *GenPoStRes) String() string { return proto.CompactTextString(m) }
func (*GenPoStRes) ProtoMessage()    {}
func (*GenPoStRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *GenPoStRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenPoStRes.Unmarshal(m, b)
}
func (m *GenPoStRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenPoStRes.Marshal(b, m, deterministic)
}
func (m *GenPoStRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenPoStRes.Merge(m, src)
}
func (m *GenPoStRes) XXX_Size() int {
	return xxx_messageInfo_GenPoStRes.Size(m)
}
func (m *GenPoStRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GenPoStRes.DiscardUnknown(m)
}

var xxx_messageInfo_GenPoStRes proto.InternalMessageInfo

type PieceMeta struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	InclusionProof       []byte   `protobuf:"bytes,3,opt,name=InclusionProof,proto3" json:"InclusionProof,omitempty"`
	CommP                []byte   `protobuf:"bytes,4,opt,name=CommP,proto3" json:"CommP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieceMeta) Reset()         { *m = PieceMeta{} }
func (m *PieceMeta) String() string { return proto.CompactTextString(m) }
func (*PieceMeta) ProtoMessage()    {}
func (*PieceMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *PieceMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceMeta.Unmarshal(m, b)
}
func (m *PieceMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceMeta.Marshal(b, m, deterministic)
}
func (m *PieceMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceMeta.Merge(m, src)
}
func (m *PieceMeta) XXX_Size() int {
	return xxx_messageInfo_PieceMeta.Size(m)
}
func (m *PieceMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PieceMeta proto.InternalMessageInfo

func (m *PieceMeta) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PieceMeta) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PieceMeta) GetInclusionProof() []byte {
	if m != nil {
		return m.InclusionProof
	}
	return nil
}

func (m *PieceMeta) GetCommP() []byte {
	if m != nil {
		return m.CommP
	}
	return nil
}

type SealResultRes struct {
	Got                  bool     `protobuf:"varint,1,opt,name=Got,proto3" json:"Got,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SealResultRes) Reset()         { *m = SealResultRes{} }
func (m *SealResultRes) String() string { return proto.CompactTextString(m) }
func (*SealResultRes) ProtoMessage()    {}
func (*SealResultRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *SealResultRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SealResultRes.Unmarshal(m, b)
}
func (m *SealResultRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SealResultRes.Marshal(b, m, deterministic)
}
func (m *SealResultRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SealResultRes.Merge(m, src)
}
func (m *SealResultRes) XXX_Size() int {
	return xxx_messageInfo_SealResultRes.Size(m)
}
func (m *SealResultRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SealResultRes.DiscardUnknown(m)
}

var xxx_messageInfo_SealResultRes proto.InternalMessageInfo

func (m *SealResultRes) GetGot() bool {
	if m != nil {
		return m.Got
	}
	return false
}

type CandidatesReq struct {
	SecSize              uint64   `protobuf:"varint,1,opt,name=SecSize,proto3" json:"SecSize,omitempty"`
	ProverID             []byte   `protobuf:"bytes,2,opt,name=ProverID,proto3" json:"ProverID,omitempty"`
	Randomness           []byte   `protobuf:"bytes,3,opt,name=Randomness,proto3" json:"Randomness,omitempty"`
	ClgCount             uint64   `protobuf:"varint,4,opt,name=ClgCount,proto3" json:"ClgCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandidatesReq) Reset()         { *m = CandidatesReq{} }
func (m *CandidatesReq) String() string { return proto.CompactTextString(m) }
func (*CandidatesReq) ProtoMessage()    {}
func (*CandidatesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

func (m *CandidatesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidatesReq.Unmarshal(m, b)
}
func (m *CandidatesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidatesReq.Marshal(b, m, deterministic)
}
func (m *CandidatesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidatesReq.Merge(m, src)
}
func (m *CandidatesReq) XXX_Size() int {
	return xxx_messageInfo_CandidatesReq.Size(m)
}
func (m *CandidatesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidatesReq.DiscardUnknown(m)
}

var xxx_messageInfo_CandidatesReq proto.InternalMessageInfo

func (m *CandidatesReq) GetSecSize() uint64 {
	if m != nil {
		return m.SecSize
	}
	return 0
}

func (m *CandidatesReq) GetProverID() []byte {
	if m != nil {
		return m.ProverID
	}
	return nil
}

func (m *CandidatesReq) GetRandomness() []byte {
	if m != nil {
		return m.Randomness
	}
	return nil
}

func (m *CandidatesReq) GetClgCount() uint64 {
	if m != nil {
		return m.ClgCount
	}
	return 0
}

type CandidatesRes struct {
	Got                  bool     `protobuf:"varint,1,opt,name=Got,proto3" json:"Got,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandidatesRes) Reset()         { *m = CandidatesRes{} }
func (m *CandidatesRes) String() string { return proto.CompactTextString(m) }
func (*CandidatesRes) ProtoMessage()    {}
func (*CandidatesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{10}
}

func (m *CandidatesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidatesRes.Unmarshal(m, b)
}
func (m *CandidatesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidatesRes.Marshal(b, m, deterministic)
}
func (m *CandidatesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidatesRes.Merge(m, src)
}
func (m *CandidatesRes) XXX_Size() int {
	return xxx_messageInfo_CandidatesRes.Size(m)
}
func (m *CandidatesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidatesRes.DiscardUnknown(m)
}

var xxx_messageInfo_CandidatesRes proto.InternalMessageInfo

func (m *CandidatesRes) GetGot() bool {
	if m != nil {
		return m.Got
	}
	return false
}

type PreResultReq struct {
	CommC                []byte   `protobuf:"bytes,1,opt,name=CommC,proto3" json:"CommC,omitempty"`
	CommD                []byte   `protobuf:"bytes,2,opt,name=CommD,proto3" json:"CommD,omitempty"`
	CommR                []byte   `protobuf:"bytes,3,opt,name=CommR,proto3" json:"CommR,omitempty"`
	CommRLast            []byte   `protobuf:"bytes,4,opt,name=CommRLast,proto3" json:"CommRLast,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreResultReq) Reset()         { *m = PreResultReq{} }
func (m *PreResultReq) String() string { return proto.CompactTextString(m) }
func (*PreResultReq) ProtoMessage()    {}
func (*PreResultReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{11}
}

func (m *PreResultReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreResultReq.Unmarshal(m, b)
}
func (m *PreResultReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreResultReq.Marshal(b, m, deterministic)
}
func (m *PreResultReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreResultReq.Merge(m, src)
}
func (m *PreResultReq) XXX_Size() int {
	return xxx_messageInfo_PreResultReq.Size(m)
}
func (m *PreResultReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PreResultReq.DiscardUnknown(m)
}

var xxx_messageInfo_PreResultReq proto.InternalMessageInfo

func (m *PreResultReq) GetCommC() []byte {
	if m != nil {
		return m.CommC
	}
	return nil
}

func (m *PreResultReq) GetCommD() []byte {
	if m != nil {
		return m.CommD
	}
	return nil
}

func (m *PreResultReq) GetCommR() []byte {
	if m != nil {
		return m.CommR
	}
	return nil
}

func (m *PreResultReq) GetCommRLast() []byte {
	if m != nil {
		return m.CommRLast
	}
	return nil
}

type PreResultRes struct {
	Got                  bool     `protobuf:"varint,1,opt,name=Got,proto3" json:"Got,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreResultRes) Reset()         { *m = PreResultRes{} }
func (m *PreResultRes) String() string { return proto.CompactTextString(m) }
func (*PreResultRes) ProtoMessage()    {}
func (*PreResultRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{12}
}

func (m *PreResultRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreResultRes.Unmarshal(m, b)
}
func (m *PreResultRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreResultRes.Marshal(b, m, deterministic)
}
func (m *PreResultRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreResultRes.Merge(m, src)
}
func (m *PreResultRes) XXX_Size() int {
	return xxx_messageInfo_PreResultRes.Size(m)
}
func (m *PreResultRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PreResultRes.DiscardUnknown(m)
}

var xxx_messageInfo_PreResultRes proto.InternalMessageInfo

func (m *PreResultRes) GetGot() bool {
	if m != nil {
		return m.Got
	}
	return false
}

type SealResultReq struct {
	Proof                []byte   `protobuf:"bytes,1,opt,name=Proof,proto3" json:"Proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SealResultReq) Reset()         { *m = SealResultReq{} }
func (m *SealResultReq) String() string { return proto.CompactTextString(m) }
func (*SealResultReq) ProtoMessage()    {}
func (*SealResultReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{13}
}

func (m *SealResultReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SealResultReq.Unmarshal(m, b)
}
func (m *SealResultReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SealResultReq.Marshal(b, m, deterministic)
}
func (m *SealResultReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SealResultReq.Merge(m, src)
}
func (m *SealResultReq) XXX_Size() int {
	return xxx_messageInfo_SealResultReq.Size(m)
}
func (m *SealResultReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SealResultReq.DiscardUnknown(m)
}

var xxx_messageInfo_SealResultReq proto.InternalMessageInfo

func (m *SealResultReq) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type CanResultReq struct {
	SecID                uint64   `protobuf:"varint,1,opt,name=SecID,proto3" json:"SecID,omitempty"`
	ParTicket            []byte   `protobuf:"bytes,2,opt,name=ParTicket,proto3" json:"ParTicket,omitempty"`
	Ticket               []byte   `protobuf:"bytes,3,opt,name=Ticket,proto3" json:"Ticket,omitempty"`
	SecChaIndex          uint64   `protobuf:"varint,4,opt,name=SecChaIndex,proto3" json:"SecChaIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanResultReq) Reset()         { *m = CanResultReq{} }
func (m *CanResultReq) String() string { return proto.CompactTextString(m) }
func (*CanResultReq) ProtoMessage()    {}
func (*CanResultReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{14}
}

func (m *CanResultReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanResultReq.Unmarshal(m, b)
}
func (m *CanResultReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanResultReq.Marshal(b, m, deterministic)
}
func (m *CanResultReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanResultReq.Merge(m, src)
}
func (m *CanResultReq) XXX_Size() int {
	return xxx_messageInfo_CanResultReq.Size(m)
}
func (m *CanResultReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CanResultReq.DiscardUnknown(m)
}

var xxx_messageInfo_CanResultReq proto.InternalMessageInfo

func (m *CanResultReq) GetSecID() uint64 {
	if m != nil {
		return m.SecID
	}
	return 0
}

func (m *CanResultReq) GetParTicket() []byte {
	if m != nil {
		return m.ParTicket
	}
	return nil
}

func (m *CanResultReq) GetTicket() []byte {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func (m *CanResultReq) GetSecChaIndex() uint64 {
	if m != nil {
		return m.SecChaIndex
	}
	return 0
}

type CanResultRes struct {
	Got                  bool     `protobuf:"varint,1,opt,name=Got,proto3" json:"Got,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanResultRes) Reset()         { *m = CanResultRes{} }
func (m *CanResultRes) String() string { return proto.CompactTextString(m) }
func (*CanResultRes) ProtoMessage()    {}
func (*CanResultRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{15}
}

func (m *CanResultRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanResultRes.Unmarshal(m, b)
}
func (m *CanResultRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanResultRes.Marshal(b, m, deterministic)
}
func (m *CanResultRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanResultRes.Merge(m, src)
}
func (m *CanResultRes) XXX_Size() int {
	return xxx_messageInfo_CanResultRes.Size(m)
}
func (m *CanResultRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CanResultRes.DiscardUnknown(m)
}

var xxx_messageInfo_CanResultRes proto.InternalMessageInfo

func (m *CanResultRes) GetGot() bool {
	if m != nil {
		return m.Got
	}
	return false
}

type PoStResultReq struct {
	MachineID            uint32   `protobuf:"varint,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	Proof                []byte   `protobuf:"bytes,2,opt,name=Proof,proto3" json:"Proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoStResultReq) Reset()         { *m = PoStResultReq{} }
func (m *PoStResultReq) String() string { return proto.CompactTextString(m) }
func (*PoStResultReq) ProtoMessage()    {}
func (*PoStResultReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{16}
}

func (m *PoStResultReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoStResultReq.Unmarshal(m, b)
}
func (m *PoStResultReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoStResultReq.Marshal(b, m, deterministic)
}
func (m *PoStResultReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoStResultReq.Merge(m, src)
}
func (m *PoStResultReq) XXX_Size() int {
	return xxx_messageInfo_PoStResultReq.Size(m)
}
func (m *PoStResultReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PoStResultReq.DiscardUnknown(m)
}

var xxx_messageInfo_PoStResultReq proto.InternalMessageInfo

func (m *PoStResultReq) GetMachineID() uint32 {
	if m != nil {
		return m.MachineID
	}
	return 0
}

func (m *PoStResultReq) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type PoStResultRes struct {
	Got                  bool     `protobuf:"varint,1,opt,name=Got,proto3" json:"Got,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoStResultRes) Reset()         { *m = PoStResultRes{} }
func (m *PoStResultRes) String() string { return proto.CompactTextString(m) }
func (*PoStResultRes) ProtoMessage()    {}
func (*PoStResultRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{17}
}

func (m *PoStResultRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoStResultRes.Unmarshal(m, b)
}
func (m *PoStResultRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoStResultRes.Marshal(b, m, deterministic)
}
func (m *PoStResultRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoStResultRes.Merge(m, src)
}
func (m *PoStResultRes) XXX_Size() int {
	return xxx_messageInfo_PoStResultRes.Size(m)
}
func (m *PoStResultRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PoStResultRes.DiscardUnknown(m)
}

var xxx_messageInfo_PoStResultRes proto.InternalMessageInfo

func (m *PoStResultRes) GetGot() bool {
	if m != nil {
		return m.Got
	}
	return false
}

func init() {
	proto.RegisterType((*PreCommitReq)(nil), "types.PreCommitReq")
	proto.RegisterType((*PublicPieceInfo)(nil), "types.PublicPieceInfo")
	proto.RegisterType((*PreCommitRes)(nil), "types.PreCommitRes")
	proto.RegisterType((*SealCommitReq)(nil), "types.SealCommitReq")
	proto.RegisterType((*SealCommitRes)(nil), "types.SealCommitRes")
	proto.RegisterType((*GenPoStReq)(nil), "types.GenPoStReq")
	proto.RegisterType((*GenPoStRes)(nil), "types.GenPoStRes")
	proto.RegisterType((*PieceMeta)(nil), "types.PieceMeta")
	proto.RegisterType((*SealResultRes)(nil), "types.SealResultRes")
	proto.RegisterType((*CandidatesReq)(nil), "types.CandidatesReq")
	proto.RegisterType((*CandidatesRes)(nil), "types.CandidatesRes")
	proto.RegisterType((*PreResultReq)(nil), "types.PreResultReq")
	proto.RegisterType((*PreResultRes)(nil), "types.PreResultRes")
	proto.RegisterType((*SealResultReq)(nil), "types.SealResultReq")
	proto.RegisterType((*CanResultReq)(nil), "types.CanResultReq")
	proto.RegisterType((*CanResultRes)(nil), "types.CanResultRes")
	proto.RegisterType((*PoStResultReq)(nil), "types.PoStResultReq")
	proto.RegisterType((*PoStResultRes)(nil), "types.PoStResultRes")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x95, 0x34, 0xed, 0x6e, 0x66, 0xd3, 0x2e, 0x32, 0x68, 0x15, 0xa1, 0x0a, 0x75, 0x2d,
	0x81, 0x7a, 0xaa, 0x16, 0x38, 0x72, 0x4c, 0xa5, 0x55, 0x04, 0x2b, 0x45, 0x0e, 0x2f, 0xe0, 0xa6,
	0xb3, 0x6c, 0x44, 0x6b, 0x97, 0x38, 0x05, 0x16, 0x71, 0xe1, 0x65, 0x78, 0x28, 0x9e, 0x06, 0xc5,
	0x76, 0x1a, 0xa7, 0xaa, 0x38, 0x73, 0xf3, 0x3f, 0xf6, 0x64, 0xbe, 0x7f, 0xc6, 0x0e, 0x44, 0x85,
	0xdc, 0x6e, 0xa5, 0x58, 0xec, 0x2a, 0x59, 0x4b, 0x32, 0xac, 0x1f, 0x77, 0xa8, 0xe8, 0x6f, 0x0f,
	0xa2, 0xac, 0xc2, 0x44, 0x6e, 0xb7, 0x65, 0xcd, 0xf0, 0x0b, 0x89, 0xe1, 0x2c, 0xc7, 0x22, 0x2f,
	0x7f, 0x60, 0xec, 0xcd, 0xbc, 0x79, 0xc0, 0x5a, 0x49, 0x9e, 0xc1, 0x30, 0xc7, 0x22, 0x5d, 0xc6,
	0xbe, 0x8e, 0x1b, 0x41, 0x9e, 0xc3, 0x79, 0x56, 0xc9, 0xaf, 0x58, 0xa5, 0xcb, 0x78, 0x30, 0xf3,
	0xe6, 0x11, 0x3b, 0xe8, 0xe6, 0x5b, 0x1f, 0xcb, 0xe2, 0x33, 0xd6, 0x2a, 0x0e, 0xf4, 0x56, 0x2b,
	0xc9, 0x0d, 0x9c, 0x65, 0xfb, 0x55, 0x2a, 0xee, 0x65, 0x3c, 0x9c, 0x0d, 0xe6, 0x17, 0x6f, 0xae,
	0x16, 0x9a, 0x67, 0x91, 0xed, 0x57, 0x9b, 0xb2, 0xc8, 0x4a, 0x2c, 0xb0, 0xd9, 0x65, 0xed, 0x31,
	0xfa, 0x0e, 0x2e, 0x8f, 0xf6, 0x08, 0x81, 0xc0, 0xe1, 0x0c, 0x5a, 0xc8, 0xc6, 0x4b, 0xa6, 0x21,
	0x23, 0x66, 0x04, 0x9d, 0xf4, 0x4c, 0x2a, 0xfa, 0xc7, 0x83, 0x71, 0x8e, 0x7c, 0xf3, 0xdf, 0xdb,
	0x26, 0xaf, 0x21, 0x64, 0xfc, 0x9b, 0xe1, 0x8c, 0x47, 0x3a, 0xe7, 0x69, 0x9b, 0x53, 0x21, 0x43,
	0xb5, 0xdf, 0x34, 0xfc, 0xac, 0x3b, 0x45, 0x2f, 0xfb, 0xde, 0x14, 0xbd, 0x01, 0xb8, 0x45, 0x91,
	0xc9, 0x5c, 0x3b, 0x9d, 0x80, 0x9f, 0xee, 0xb4, 0xc9, 0x88, 0xf9, 0xe9, 0x4e, 0x77, 0x11, 0x71,
	0x6d, 0x1b, 0xa6, 0xd7, 0x34, 0x72, 0x32, 0x14, 0x95, 0x10, 0x6a, 0xb2, 0x3b, 0xac, 0x39, 0x79,
	0x02, 0x83, 0xf7, 0xf8, 0xa8, 0xf3, 0x43, 0xd6, 0x2c, 0x0f, 0x63, 0xf0, 0x9d, 0x31, 0xbc, 0x82,
	0x49, 0x2a, 0x8a, 0xcd, 0x5e, 0x95, 0x52, 0x64, 0x95, 0x94, 0xf7, 0xb6, 0x49, 0x47, 0xd1, 0x6e,
	0x5c, 0x81, 0x3b, 0xae, 0x6b, 0xe3, 0xa0, 0x75, 0xa7, 0x9a, 0xa2, 0xb7, 0xb2, 0xd6, 0x45, 0xcf,
	0x59, 0xb3, 0xa4, 0xbf, 0x3c, 0x18, 0x27, 0x5c, 0xac, 0xcb, 0x35, 0xaf, 0x51, 0xfd, 0x7b, 0x82,
	0xee, 0xac, 0xfc, 0xa3, 0x59, 0xbd, 0x00, 0x60, 0x5c, 0xac, 0xe5, 0x56, 0xa0, 0x52, 0x16, 0xd2,
	0x89, 0x34, 0xb9, 0xc9, 0xe6, 0x53, 0x22, 0xf7, 0xa2, 0xd6, 0x8c, 0x01, 0x3b, 0xe8, 0x06, 0xd3,
	0x45, 0x38, 0x85, 0x29, 0xf4, 0xc5, 0x3b, 0x8c, 0xa9, 0xf5, 0x9b, 0xd8, 0xfe, 0x1b, 0xd1, 0x46,
	0x97, 0xee, 0xa5, 0x5d, 0xb6, 0x51, 0x66, 0xa9, 0x8c, 0x20, 0x53, 0x08, 0xf5, 0xe2, 0x03, 0x57,
	0xb5, 0xed, 0x5a, 0x17, 0xa0, 0xb3, 0x5e, 0xbd, 0x53, 0x44, 0x2f, 0xfb, 0xbd, 0xd5, 0x48, 0x66,
	0x42, 0x16, 0x49, 0x0b, 0xfa, 0x13, 0xa2, 0x84, 0x8b, 0xde, 0x29, 0xf3, 0x0a, 0x3c, 0xf7, 0x15,
	0x4c, 0x21, 0xcc, 0x78, 0x65, 0x6e, 0xb7, 0x85, 0xef, 0x02, 0xe4, 0x0a, 0x46, 0x76, 0xcb, 0x38,
	0xb0, 0x8a, 0xcc, 0xe0, 0x22, 0xc7, 0x22, 0x79, 0xe0, 0xa9, 0x58, 0xe3, 0x77, 0xdb, 0x56, 0x37,
	0xd4, 0xd8, 0x70, 0xaa, 0x9f, 0xb2, 0x91, 0xc0, 0xd8, 0x5e, 0x4f, 0x0b, 0x38, 0x85, 0xf0, 0x8e,
	0x17, 0x0f, 0xa5, 0x40, 0x0b, 0x39, 0x66, 0x5d, 0xa0, 0x33, 0xe9, 0xbb, 0x26, 0xaf, 0xfb, 0x1f,
	0x39, 0x51, 0x67, 0x35, 0xd2, 0x7f, 0xcb, 0xb7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x37, 0xa3,
	0x91, 0x62, 0x3d, 0x05, 0x00, 0x00,
}
